version: '2'
services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:latest'
    volumes:
      - /path/to/mariadb-persitence:/bitnami/mariadb
    environment:
      - MARIADB_USER=nami
      - MARIADB_PASSWORD=janna
      - MARIADB_DATABASE=humhub_db
      - ALLOW_EMPTY_PASSWORD=yes
  humhub:
    image: 'frapazgal/humhub_mariadb:latest'
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - /path/to/humhub-persistence:/var/www/humhub
    depends_on:
      - mariadb
    environment:
      - HH_MARIADB_HOST=mariadb
