apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: humhub-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: humhub
  template:
    metadata:
      labels:
        app: humhub
    spec:
      securityContext:
        runAsUser: 1001
        fsGroup: 0
      containers:
      - name: humhub-container
        image: frapazgal/humhub:1.4.3-r1
        ports:
        - containerPort: 8080
          name: http
        volumeMounts:
        - mountPath: "/var/www/humhub"
          name: humhub-data
        imagePullPolicy: Always
      volumes:
      - name: humhub-data
        persistentVolumeClaim:
          claimName: humhub-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: humhub-service
spec:
  selector:
    app: humhub
  ports:
  - protocol: TCP
    targetPort: 8080
    port: 80
    name: http
  type: LoadBalancer
