apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mariadb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb-app
  template:
    metadata:
      labels:
        app: mariadb-app
    spec:
      securityContext:
        runAsUser: 1001
        fsGroup: 1001
      containers:
      - name: mariadb-container
        image: bitnami/mariadb:10.5.4-debian-10-r4
        ports:
        - containerPort: 3306
        env:
        - name: MARIADB_USER
          value: "nami"
        - name: MARIADB_PASSWORD
          value: "janna"
        - name: MARIADB_DATABASE
          value: "humhub_db"
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        volumeMounts:
        - mountPath: "/bitnami/mariadb"
          name: mariadb-data
      volumes:
      - name: mariadb-data
        persistentVolumeClaim:
          claimName: mariadb-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  selector:
    app: mariadb-app
  ports:
  - protocol: TCP
    port: 3306
  type: ClusterIP
